"""Generate valid podcast RSS feeds from source data."""

from __future__ import annotations

import sqlite3
from datetime import datetime, timezone


def generate_feed(
    source: sqlite3.Row,
    videos: list[sqlite3.Row],
    base_url: str,
) -> str:
    """Generate a podcast-compatible RSS feed for a source.

    Args:
        source: Source row from the database.
        videos: List of completed video rows (with file_path and file_size).
        base_url: The server's base URL (e.g. http://192.168.1.5:8642).

    Returns:
        RSS XML string.
    """
    from feedgen.feed import FeedGenerator  # Lazy import — lxml is slow to load

    fg = FeedGenerator()
    fg.load_extension("podcast")

    source_id = source["id"]
    source_name = source["name"]

    fg.title(source_name)
    fg.description(f"Podcast feed for {source_name} — generated by PodcastSync")
    fg.language("en")
    fg.generator("PodcastSync")

    feed_url = f"{base_url}/feed/{source_id}.xml"
    fg.link(href=source["url"], rel="alternate")
    fg.link(href=feed_url, rel="self")

    # Podcast-specific metadata
    fg.podcast.itunes_author(source_name)
    fg.podcast.itunes_summary(f"Audio from {source_name} YouTube {source['source_type']}")
    fg.podcast.itunes_explicit("no")

    # Prefer channel icon as feed image; fall back to first video thumbnail
    icon = source["icon_url"] or (videos[0]["thumbnail_url"] if videos else None)
    if icon:
        fg.image(url=icon, title=source_name)
        fg.podcast.itunes_image(icon)

    for row in videos:
        fe = fg.add_entry()

        video_id = row["video_id"]
        fe.id(video_id)
        fe.title(row["title"])
        fe.description(row["description"] or row["title"])

        # Publish date
        pub_str = row["publish_date"]
        if pub_str:
            try:
                pub = datetime.fromisoformat(pub_str)
                if pub.tzinfo is None:
                    pub = pub.replace(tzinfo=timezone.utc)
                fe.published(pub)
            except ValueError:
                pass

        # YouTube link
        fe.link(href=f"https://www.youtube.com/watch?v={video_id}")

        # Audio enclosure
        file_size = row["file_size"] or 0
        audio_url = f"{base_url}/audio/{source_id}/{video_id}.mp3"
        fe.enclosure(audio_url, str(file_size), "audio/mpeg")

        # Duration
        duration = row["duration_seconds"]
        if duration:
            fe.podcast.itunes_duration(duration)

        # Thumbnail as episode image
        thumb = row["thumbnail_url"]
        if thumb:
            fe.podcast.itunes_image(thumb)

        fe.podcast.itunes_explicit("no")

    return fg.rss_str(pretty=True).decode("utf-8")
